[versions]
agp = "8.6.0"
appcompatVersion = "1.6.0"
cardview = "1.0.0"
commonsCollections4 = "4.4"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
poi = "5.2.3"
xmlbeans = "5.0.2"
xmlbeansVersion = "5.1.1"
lifecycleLivedataKtx = "2.8.5"
lifecycleViewmodelKtx = "2.8.5"
viewpager2 = "1.0.0"

[libraries]
appcompat-v160 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollections4" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
xmlbeans = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeans" }
xmlbeans-v511 = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeansVersion" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
viewpager2 = "androidx.viewpager2:viewpager2:${versions.viewpager2}"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

